// API Configuration - Auto-generated by Vercel build
// This file is overwritten during Vercel deployment with the configured VITE_API_BASE_URL
// For local development, it uses the default same-origin API (/api/v1)
// For production, set VITE_API_BASE_URL environment variable in Vercel project settings

// Uncomment the line below and set your production API URL for testing locally with a remote backend:
// window.__API_BASE_URL = 'https://your-backend-url.com/api/v1';
